#!/data/data/com.termux/files/usr/bin/zsh

# This script take's ngrok full generated url to split the host and it's port in order to ssh connection.

host=${1%:*}
port=${1#*:}

echo host $host
echo port $port

ssh muss@$host -p $port
